# shallow clone
clone_depth: 5

platform:
  - x64

environment:
  global:
    MSYS2_ARCH: x86_64
  matrix:
    - HOST_ARCH_ARG: --host=x86_64-w64-mingw32
      ADD_PATH: /mingw64/bin

  BUILD_PASSWORD:
    secure: EXGNlWKJsCtbeImEJ5EP9qrxZ+EqUFfNy+CP61nDOMA=

install:
  - git submodule update --init --recursive
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Suy make pkg-config mingw-w64-x86_64-glib2 mingw-w64-x86_64-toolchain mingw64/mingw-w64-x86_64-qt5-static mingw64/mingw-w64-x86_64-SDL2"

before_build:
  - mkdir build
  - cmake -G "MSYS Makefiles" -DMINGW_STATIC_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DQt5_DIR=C:/msys64/mingw64/qt5-static/lib/cmake/Qt5/ ..

build_script:
  - cd build && make VERBOSE=1 && cd ..

test_script:
  - cd build && ctest -VV -C Release && cd ..

on_success:
    # copying the needed QT Dlls is now done post build. See the CMakeLists.txt file in the citra-qt folder
  - ps: >
        if (!"$env:APPVEYOR_PULL_REQUEST_TITLE" -and ("$env:APPVEYOR_REPO_BRANCH" -eq "master"))
          {
            $GITDATE = $(git show -s --date=short --format='%ad') -replace "-",""
            $GITREV = $(git show -s --format='%h')
            # Where are these spaces coming from? Regardless, let's remove them
            $BUILD_NAME = "citra-${GITDATE}-${GITREV}-windows-amd64.7z" -replace " ",""
            $BUILD_NAME_NOQT = "citra-noqt-${GITDATE}-${GITREV}-windows-amd64.7z" -replace " ",""
            # Zip up the build folder and documentation
            7z a $BUILD_NAME .\build\bin\release\* .\license.txt .\README.md
            # Do a second archive with only the binaries (excludes dlls) and documentation
            7z a $BUILD_NAME_NOQT .\build\bin\release\*.exe .\license.txt .\README.md


            # Download WinSCP and upload to server
            choco install winscp.portable
            WinSCP.exe /command `
                "option batch abort" `
                "option confirm off" `
                "open sftp://citra-builds:${env:BUILD_PASSWORD}@builds.citra-emu.org -hostkey=*" `
                "put $BUILD_NAME /citra/nightly/windows-amd64/" `
                "put $BUILD_NAME_NOQT /citra/nightly/windows-noqt-amd64/" `
                "exit"
          }
