# shallow clone
clone_depth: 10

# don't build on tag
skip_tags: true

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DCITRA_USE_BUNDLED_QT=1 -DCITRA_USE_BUNDLED_SDL2=1 ..
  - cd ..

build:
  project: build/citra.sln
  parallel: true

after_build:
  - ps: |
        $GIT_SHORT_NAME = $(git show -s --format='%h')
        $MSVC_BUILD_NAME = "citra-windows-msvc-amd64-$GIT_SHORT_NAME.zip"
        $MSVC_BUILD_PDB = "citra-windows-msvc-amd64-$GIT_SHORT_NAME-debugsymbols.zip"

        # set the build names as env vars so the artifacts can upload them
        $env:MSVC_BUILD_NAME = $MSVC_BUILD_NAME
        $env:MSVC_BUILD_PDB = $MSVC_BUILD_PDB

        7z a -tzip $MSVC_BUILD_PDB .\build\bin\release\*.pdb
        rm .\build\bin\release\*.pdb
        7z a -tzip $MSVC_BUILD_NAME .\build\bin\release\* .\license.txt .\README.md

test_script:
  - cd build && ctest -VV -C Release && cd ..

artifacts:
  - path: $(MSVC_BUILD_NAME)
    name: msvcbuild
    type: zip
  - path: $(MSVC_BUILD_PDB)
    name: msvcdebug
    type: zip

deploy:
- provider: BinTray
  username: jroweboy
  api_key:
    secure: EWw3I8nD+Y4FT82MDxnKnbgvnJTSFHPSFLtDIPr4VKqB2EfDnm73dZWr5DqbOGtV
  subject: jroweboy
  repo: citra-test-jroweboy
  package: citra-nightly
  version: windows
  publish: true
