# shallow clone
clone_depth: 10

# don't build on tag
skip_tags: true

deploy:
  - provider: GitHub
    release: nightly-$(appveyor_build_number)
    description: |
      Download and extract the zip file for your operating system and run citra-qt

      Nightly Build number $(appveyor_build_number)
    auth_token:
      secure: MeBSKRVxvUlkHpCbV+PhpGMmvM2Xh4gkjf4/gWvCtl1ix/VJQPbs7L/PNU7IS66C
    artifact: msvcbuild,msvcdebug
    draft: false
    prerelease: false
    on:
      branch: master
      # travis only releases on tag so have appveyor make the tag and let travis upload to it
      appveyor_repo_tag: true

environment:
  BUILD_PASSWORD:
    secure: EXGNlWKJsCtbeImEJ5EP9qrxZ+EqUFfNy+CP61nDOMA=

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DCITRA_USE_BUNDLED_QT=1 -DCITRA_USE_BUNDLED_SDL2=1 ..
  - cd ..

build:
  project: build/citra.sln
  parallel: true

after_build:
  - ps: |
        $GIT_SHORT_NAME = $(git show -s --format='%h')
        $MSVC_BUILD_NAME = "citra-windows-msvc-amd64-$GIT_SHORT_NAME.zip"
        $MSVC_BUILD_PDB = "citra-windows-msvc-amd64-$GIT_SHORT_NAME-debugsymbols.zip"
        # set the build names as env vars so the artifacts can upload them
        $env:MSVC_BUILD_NAME = $MSVC_BUILD_NAME
        $env:MSVC_BUILD_PDB = $MSVC_BUILD_PDB
        rm .\build\bin\release\*tests*
        7z a -tzip $BUILD_NAME_PDB .\build\bin\release\*.pdb
        rm .\build\bin\release\*.pdb
        7z a -tzip $BUILD_NAME .\build\bin\release\* .\license.txt .\README.md

test_script:
  - cd build && ctest -VV -C Release && cd ..

artifacts:
  - msvcbuild: $(MSVC_BUILD_NAME)
  - msvcdebug: $(MSVC_BUILD_PDB)